// import "@ant-design/v5-patch-for-react-19";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ToastContainer } from "react-toastify";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "@/styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
    "900", // Black
  ],
});

export const metadata: Metadata = {
  title: "iCORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased text-sm font-normal leading-4`}
      >
        <NuqsAdapter>
          {/* <AntdRegistry> */}
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#059669",
                  fontSize: 14,
                  fontFamily: "'Inter', sans-serif",
                  controlOutline: "rgba(16, 185, 129, 0.2)",
                  controlOutlineWidth: 2,
                },
                components: {
                  Input: {
                    activeBorderColor: "#059669",
                    fontSize: 14,
                    colorTextPlaceholder: "#9CA3AF",
                  },
                  Select: {
                    optionSelectedBg: "#d1fae5",
                    fontSize: 14,
                  },
                  DatePicker: {
                    activeBorderColor: "#059669",
                    fontSize: 14,
                  },
                },
              }}
            >
              {children}
            </ConfigProvider>
          {/* </AntdRegistry> */}
        </NuqsAdapter>

        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar
          theme="colored"
        />
      </body>
    </html>
  );
}
